apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: moment-tech-oss
    labels:
        app.kubernetes.io/name: persistent-audio-widget-spike
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:y5v4HoO5AAKrMRgum2a9X1Ot4f85xxv7BUcduorigQ8d3PzjxxCXnTdrxhGXMB7G4UZ8Hy0H27ADjfi/nnLEFFEv7fjQm8VavqHIlPm4EB4x3Uy0AbCWr8l9fhUp1DG6eOMFpdoyHbPYkH2m8uuGbwbJG0BsOs14hwWXEpd/ptlqtXf2RjQth+MKvdRzFXFcRuAgY4ANZiNPC8K0hPbDocb5FJyDSUnpIEq09wQ4,iv:EYAPpG3MiLNQK/dOoIUEBIgy8/GN7OXRJfI8+bY9uAs=,tag:cLSvAc1LdSqvcrdDi9EqVw==,type:str]
sops:
    age:
        - recipient: age1zexdd6jgd7j4nh4dzn4umtu0ejpunghyhq9fxqvlt0u0sfeclpgq2d7m2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QUhnc2R2eVhtazFhTUpU
            Z3NXYVF3cndiTXFQRmRMSGswTVBnQkMyVTFzCk5HSXJKNklkUkNzd1hPWS84Z1lJ
            NXJZVFJkVkpObTBWZ2s0RkxURGFDemMKLS0tIGpqaktLenI4WUNrSktSS0F4MjJZ
            SVFnQ0JTeUhwck9Ybkx3ZFROblZSU3MKsNPlHxzC5Ul4YppX8zmoiNQ+abeLxRBI
            t87VAppET53LoNduBUacJM4luCmb+EgU/LPf1a0mdpc36sR1p3v09A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T16:15:39Z"
    mac: ENC[AES256_GCM,data:ul8R0+GBZC2XCer6I+Jw8nGatYKFPZ/9fnIWgqVZTB4OiVf+IuBKFjY+OVnZDbfw5V4kX+1AWspfjUwkMfmu++J1dHv2NMdNGcEdWSrK5n3kw76QdgQ8Cdt5sErVF/vV9G/r3ce1DKT53dLuo0MJopgC7rA2s/kTeweY7u2zmX8=,iv:78B9fggHEmEige/bH8MStlik4U5ak9seHwHdxTkO1gY=,tag:5extjIjqIGFtwDNYiCmwjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
